language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install .
script:
- election_results_xml_validator list
- python setup.py test
deploy:
  provider: pypi
  user: civics-partner-data
  password:
    secure: RcDJxwgbRrtS8FJ+E4vWFWYOa4h5E8dA9oXIJZkN78TMjhQSL0CXNNxvLj8RfeCjRrRdoE87bmBIE18UypRk+SloBZeGovRC3yzD5jMiRMMKieQL0vmEw+MGTuRscbC8yaMVD8a5ZwJfensSAYpcp+vThUIM84xLyI6HFamm9IMSwq8wG8mt35iQSl45RkUUiOBtgCydMQhNdufDimkxnDRaBU9kpFHLxL//8aD4wrVFjRcq1Ub71Y49En5YhcXLpiw3bvgK9dh27F1XqJYcc13EOzrcL5d1MUH8blrPjYQNkg9yDzab/urdlMf5HqUo6WzwuV58YfxDgKQAo01pnEIGj6ejEyhDMnQ9//rAHvPO1LvmZvWMkiBIfFQR/3lWX2XdtTNCUK+fLppWV2lxX8pGqEem9ztXkw+eMG3NWDiWyiScK9YdqjXm19nHrhTOUJDiwpaPVik6LW8ch6w1SlY6HNIGdGnmdabRzD90TqN8jGgCYkM9hZArPCKdYnbHtTnfrltowNBvZvfb1NLDBhiKHW60y0xe1Lt2sA6y4jL6CECoZWrX5kP/ocBTXObbCmQrZgRhmp8dMPm6g1UxAKcnM9K+qFb3smXRBndUT+K22UnZA4rjjJeHr1nP+xmQNyeB15mP75/CV5JXVX3N8grz7Xpnq9Dt2S3katNxroQ=
  on:
    branch: master
  skip_existing: true
- os: windows
  language: sh
  python: "3.7"
  before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
